

Q1.What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS total_revenue
FROM customer
Group BY gender;


Q2.Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id, purchase_amount
FROM customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount)
from customer)


Q3.Which are the top 5 products with the highest average review rating?

SELECT TOP 5
    item_purchased,
    ROUND(AVG(review_rating), 2) AS [Average Product Rating]
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC;


Q4.Compare the average purchase amount between Standard and Express shipping.

SELECT shipping_type,ROUND(AVG(purchase_amount),2)
FROM customer
where shipping_type in ('Standard','Express')
group by shipping_type;


Q5.Do subscribed customers spend more? Compare:

Total number of customers
Average purchase amount
Total revenue

between subscribers and non-subscribers.

SELECT subscription_status,
Count(customer_id) as total_customer,
Round(AVG(purchase_amount),2) as avg_spend,
Round(SUM(purchase_amount),2) as total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue , avg_spend DESC;


Q6.Which 5 products have the highest percentage of purchases where a discount was applied?

SELECT TOP 5
item_purchased,
ROUND (100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) ,2) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC;


Q7.Segment customers into the following groups based on their previous purchases:

New
Returning
Loyal

Then show the number of customers in each segment.

WITH customer_type AS(
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
FROM customer)

SELECT customer_segment, COUNT(*) AS No_of_customer
FROM customer_type
GROUP BY customer_segment;


Q8.What are the top 3 most purchased products within each category?

WITH item_counts AS(
SELECT category, item_purchased, COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer 
GROUP BY category , item_purchased)

SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;


Q9.Are repeat buyers (customers with more than 5 previous purchases) also likely to subscribe?


SELECT subscription_status, COUNT(customer_id) AS repeat_buyer
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

Q10.What is the revenue contribution of each age group?

SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;